moocs/moocs-web/src/main/java/moocsWeb/ExamenBean.java
package moocsWeb;

import java.io.IOException;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.sql.rowset.serial.SerialBlob;
import javax.sql.rowset.serial.SerialException;

import org.primefaces.model.UploadedFile;

import moocs.ejb.bisness.IBadgeLearnerLocal;
import moocs.ejb.bisness.ICertificateLearnerLocal;
import moocs.ejb.bisness.ICertificateLocal;
import moocs.ejb.bisness.IExamenLocal;
import moocs.ejb.bisness.IQuestionLocal;
import moocs.ejb.bisness.IUserLocal;
import moocs.ejb.entity.Answer;
import moocs.ejb.entity.Certificate;
import moocs.ejb.entity.Examen;
import moocs.ejb.entity.Learner;
import moocs.ejb.entity.Qcm;
import moocs.ejb.entity.Question;

@ManagedBean
@SessionScoped
public class ExamenBean {

	@EJB
	IExamenLocal serExamen;
	@EJB
	IQuestionLocal serQuestion;
	@EJB
	ICertificateLocal ser;
	@EJB
	ICertificateLearnerLocal serBL;
	@EJB
	IUserLocal serUser;
	private String nameCertificate;
	private UploadedFile file1;
	private List<Examen> Examens;
	private List<Question> questions;
	private List<Learner> learners;
	private List<Answer> answers;
	private Examen qui;
	private List<Answer> chosen;
	private int ExamenScore;
	private String name;
	private int note;
	private int qnumber;
	private boolean displayQuestion;
	private boolean displayall = true;
	private boolean displayUpdate;
	private boolean displayExamen;
	private boolean displayScore;
	private List<String> mychoix = new ArrayList<String>();

	@PostConstruct
	public void init() {
		questions = new ArrayList<Question>();
		for (int i = 0; i < 20; i++) {
			mychoix.add("");
		}

	}

	public List<Question> getQuestions() {
		return questions;
	}

	public void setQuestions(List<Question> questions) {
		this.questions = questions;
	}

	public int getQnumber() {
		return qnumber;

	}

	public void setQnumber(int qnumber) {
		this.qnumber = qnumber;
	}

	public String doDelete() {
		serExamen.remove(qui);
		return "/examen/trainer/list?faces-redirect=true";
	}


	public String doUpdate() {
		serExamen.update(qui);
		return "/examen/trainer/list?faces-redirect=true";
	}
	public String doRenderTake()
	{
		return"/examen/learner/takeExamen?faces-redirect=true";
	}

	public String doTake() {
		ExamenScore = 0;
		for (String g : mychoix) {
			if (g.equals("true")) {
				ExamenScore++;
			}
		}
		if (ExamenScore>=note)
		{
			HttpServletRequest req = (HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
			Authentification auth=(Authentification) req.getSession().getAttribute("authentification");
			serBL.addCertificateLearner(qui.getCertificate(), (Learner)serUser.authenticate(auth.getEmail(),auth.getPassword()), ExamenScore);
		}
		return "/examen/trainer/list?faces-redirect=true";
	}

	public String doAdd() throws IOException, SerialException, SQLException {
		Examen q = new Examen();
		q.setName(name);
		q.setSuccessExamen(note);
		q.setQuestions(questions);

		serExamen.addExamen(q);
		q = serExamen.affExamen(q);
		Qcm qcm = serExamen.affQcm(q);
		for (Question quest : questions) {

			quest.setQcm(qcm);
			quest = serQuestion.affQuestion(quest);
		}
		q.setQuestions(questions);
		for (Question quest : questions) {
			answers = quest.getAnswers();
			for (Answer anser : answers) {
				anser.setQuestion(quest);
			}
			quest.setAnswers(answers);
		}
		serExamen.update(q);
		Certificate b1 = new Certificate();
		b1.setNameCertificate(nameCertificate);
		b1.setImage(ConverteBYTEtoBloob(file1.getContents()));
		ser.addCertificate(b1);
		b1 = ser.affCertificate(b1);
		b1.setExamen(q);
		ser.update(b1);
		return "/examen/trainer/list?faces-redirect=true";

	}

	private Blob ConverteBYTEtoBloob(byte[] contents) throws SerialException, SQLException {

		return new SerialBlob(contents);
	}

	public String displayQuestion() {
		displayQuestion = true;

		for (int i = 0; i < qnumber; i++) {
			Question q = new Question();
			answers = new ArrayList<Answer>();
			Answer a1 = new Answer();
			Answer a2 = new Answer();
			Answer a3 = new Answer();
			Answer a4 = new Answer();
			answers.add(a1);
			answers.add(a2);
			answers.add(a3);
			answers.add(a4);
			q.setAnswers(answers);
			questions.add(q);

		}
		return null;
	}

	public boolean isDisplayQuestion() {
		return displayQuestion;
	}

	public void setDisplayQuestion(boolean displayQuestion) {
		this.displayQuestion = displayQuestion;
	}

	public List<Answer> getAnswers() {
		return answers;
	}

	public void setAnswers(List<Answer> answers) {
		this.answers = answers;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isDisplayall() {
		return displayall;
	}

	public void setDisplayall(boolean displayall) {
		this.displayall = displayall;
	}

	public boolean isDisplayUpdate() {
		return displayUpdate;
	}

	public void setDisplayUpdate(boolean displayUpdate) {
		this.displayUpdate = displayUpdate;
	}

	public List<Examen> getExamens() {
		Examens = serExamen.afficherAllExamen();
		return Examens;
	}

	public void setExamens(List<Examen> Examens) {
		this.Examens = Examens;
	}

	public int getNote() {
		return note;
	}

	public void setNote(int note) {
		this.note = note;
	}

	public Examen getQui() {
		return qui;
	}

	public void setQui(Examen qui) {
		this.qui = qui;
	}

	public boolean isDisplayExamen() {
		return displayExamen;
	}

	public void setDisplayExamen(boolean displayExamen) {
		this.displayExamen = displayExamen;
	}

	public List<Answer> getChosen() {
		return chosen;
	}

	public void setChosen(List<Answer> chosen) {
		this.chosen = chosen;
	}

	public int getExamenScore() {
		return ExamenScore;
	}

	public void setExamenScore(int ExamenScore) {
		this.ExamenScore = ExamenScore;
	}

	public boolean isDisplayScore() {
		return displayScore;
	}

	public void setDisplayScore(boolean displayScore) {
		this.displayScore = displayScore;
	}

	public List<String> getMychoix() {
		return mychoix;
	}

	public void setMychoix(List<String> mychoix) {
		this.mychoix = mychoix;
	}

	public UploadedFile getFile1() {
		return file1;
	}

	public void setFile1(UploadedFile file1) {
		this.file1 = file1;
	}

	public String getnameCertificate() {
		return nameCertificate;
	}

	public void setnameCertificate(String nameCertificate) {
		this.nameCertificate = nameCertificate;
	}

	public List<Learner> getLearners() {
		return learners;
	}

	public void setLearners(List<Learner> learners) {
		this.learners = learners;
	}

}

moocs/moocs-web/src/main/java/moocsWeb/TrainerBean.java
package moocsWeb;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.primefaces.event.RateEvent;

import moocs.ejb.bisness.ITrainerLocal;
import moocs.ejb.entity.Badge;
import moocs.ejb.entity.Trainer;

@ManagedBean
@SessionScoped
public class TrainerBean {
	
	@EJB
	ITrainerLocal ser ;
	private String name ;
	private int id ;
	private String firstname ;
	private String lastname ;
	private String email ;
	private List<Trainer> trainers ;
	private List<Trainer> trainersRech ;
	private List<Trainer> trainersPop ;
	private boolean list_aff = true;
	private Trainer selectedTrainer ;
	private Integer rating ;
	private int note ;

	
	@PostConstruct
	public void init(){
		selectedTrainer= new Trainer() ;
		
	}
	
	public Integer getRating() {
		return rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}
	
	
public String showSearch(){
		
		return "/trainer/listTrainerRecherche?faces-redirect=true";
	}

	
	public String showProfile(){
		
		return "/trainer/profileTrainer?faces-redirect=true";
	}
	
	
	public String showCourseTrainer(){
		
		
		return "/course/displayCoursesLearn?faces-redirect=true";
	}
	
	public String doNote(){
		
		if (selectedTrainer.getNote()==0)
			note=rating;
		else 
		{
			float a = (selectedTrainer.getNote()+rating)/2 ;
			note = (int) a ;
		System.out.println(selectedTrainer.getNote());
		}
		selectedTrainer.setNote(note);
		ser.updateTrainer(selectedTrainer);
		
		return "/trainer/profileTrainer?faces-redirect=true" ;
	}
	
	
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getFirstname() {
		return firstname;
	}
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	public String getLastname() {
		return lastname;
	}
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public List<Trainer> getTrainers() {
		trainers=ser.listalltrainer();
		return trainers;
	}
	public void setTrainers(List<Trainer> trainers) {
		this.trainers = trainers;
	}
	public List<Trainer> getTrainersRech() {
		trainersRech=ser.findAllTrainerName(name);
		return trainersRech;
	}
	public void setTrainersRech(List<Trainer> trainersRech) {
		this.trainersRech = trainersRech;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public boolean isList_aff() {
		return list_aff;
	}
	public void setList_aff(boolean list_aff) {
		this.list_aff = list_aff;
	}
	
	public Trainer getSelectedTrainer() {
		return selectedTrainer;
	}
	public void setSelectedTrainer(Trainer selectedTrainer) {
		this.selectedTrainer = selectedTrainer;
	}

	public int getNote() {
		return note;
	}

	public void setNote(int note) {
		this.note = note;
	}

	public List<Trainer> getTrainersPop() {
		trainersPop=ser.findPopularTrainer();
		return trainersPop;
	}

	public void setTrainersPop(List<Trainer> trainersPop) {
		this.trainersPop = trainersPop;
	}
	
	
	
	

}

moocs/moocs-web/src/main/webapp/examen/trainer/addExamen.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:p="http://primefaces.org/ui"
	template="/template/mainPage.xhtml">
	<ui:define name="title">
		<h:outputText value="ajout d'un examen" />
	</ui:define>
	<!-- we'r going to use the name of the logged in person -->
	<ui:define name="user_name">
		<h:outputText value="#{authentification.email}" />
	</ui:define>
	<ui:define name="email">
		<h:outputText value="#{authentification.email}" />
	</ui:define>
	<ui:define name="content">
		<h:form enctype="multipart/form-data">
			<h:outputLabel value="Name examen" />
			<h:inputText value="#{examenBean.name}" class="form-control" />
			<h:outputLabel value="Certificate Name"  />
			<h:inputText value="#{examenBean.nameCertificate}"  />
			<br />
			 <p:fileUpload value="#{examenBean.file1}" mode="simple" skinSimple="true"/>
			 <br />
			<h:outputLabel value="Note de passage" />
			<h:inputText value="#{examenBean.note}" class="form-control" />
			<h:outputLabel value="question number" />
			<h:inputText value="#{examenBean.qnumber}" />
			<h:commandButton action="#{examenBean.displayQuestion()}"
				value="Display" />
			<br />
			<h:column>
				<c:forEach var="item" items="#{examenBean.questions}"
					varStatus="loop">
					<h:outputLabel value="Question #{loop.index +1} :" />
					<h:inputText value="#{examenBean.questions[loop.index].question}"
						class="form-control" />
					<c:forEach var="item2"
						items="#{examenBean.questions[loop.index].answers}"
						varStatus="loop2">
						<h:outputLabel value="Answer #{loop2.index +1} :" />
						<h:inputText
							value="#{examenBean.questions[loop.index].answers[loop2.index].answer}"
							class="form-control" />
						<h:selectOneRadio
							value="#{examenBean.questions[loop.index].answers[loop2.index].verification}">
							<f:selectItem itemValue="true" itemLabel="true" />
							<f:selectItem itemValue="false" itemLabel="false" />
						</h:selectOneRadio>
					</c:forEach>
				</c:forEach>

			</h:column>
			<h:commandButton action="#{examenBean.doAdd()}" value="Add" />
		</h:form>
	</ui:define>

</ui:composition>

moocs/moocs-web/src/main/webapp/examen/trainer/list.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:p="http://primefaces.org/ui" template="/template/mainPage.xhtml">
	<ui:define name="title">
		<h:outputText value="afficher tout les examen" />
	</ui:define>
	<!-- we'r going to use the name of the logged in person -->
	<ui:define name="user_name">
		<h:outputText value="#{authentification.email}" />
	</ui:define>
	<ui:define name="email">
		<h:outputText value="#{authentification.email}" />
	</ui:define>

	<ui:define name="content">

		<h:form enctype="multipart/form-data">

			<c:forEach var="quiz" items="#{examenBean.examens}" varStatus="loop">
				<h:outputText value="#{examenBean.examens[loop.index].idQcm}" />
				<br />
				<h:outputText value="#{examenBean.examens[loop.index].name}" />
				<br />
				<h:outputText value="#{examenBean.examens[loop.index].certificate.nameCertificate}" />
				<br />
				<h:outputText value="#{examenBean.examens[loop.index].successExamen}" />
				<br />
				<h:commandButton styleClass="btn btn-primary btn-block btn-flat"
					action=" " value="Select" style="font-weight: bold">
					<f:setPropertyActionListener
						value="#{examenBean.examens[loop.index]}" target="#{examenBean.qui}" />
				</h:commandButton>
				<h:commandButton styleClass="btn btn-primary btn-block btn-flat"
					action="#{examenBean.doRenderTake()}" style="font-weight: bold" value="TakeExamen">
					<f:setPropertyActionListener
						value="#{examenBean.examens[loop.index]}" target="#{examenBean.qui}" />
				</h:commandButton>
			</c:forEach>

		</h:form>


	</ui:define>
</ui:composition>

moocs/moocs-web/src/main/webapp/examen/trainer/updateExamen.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:p="http://primefaces.org/ui" template="/template/mainPage.xhtml">
	<ui:define name="title">
		<h:outputText value="afficher tout les examen" />
	</ui:define>
	<!-- we'r going to use the name of the logged in person -->
	<ui:define name="user_name">
		<h:outputText value="#{authentification.email}" />
	</ui:define>
	<ui:define name="email">
		<h:outputText value="#{authentification.email}" />
	</ui:define>

	<ui:define name="content">
		<h:form>
			<h:outputLabel value="examen" />
			<h:inputText value="#{examenBean.qui.name}" class="form-control" />
			<h:outputLabel value="note de passage" />
			<h:inputText value="#{examenBean.qui.successExamen}"
				class="form-control" />
			<br />
			<c:forEach var="quests" items="#{examenBean.qui.questions}">
				<h:outputLabel value="question" />
				<h:inputText value="#{quests.question}" class="form-control" />
				<br />
				<c:forEach var="anss" items="#{quests.answers}">
					<h:outputLabel value="Answer" />
					<h:inputText value="#{anss.answer}" class="form-control" />
					<h:selectOneRadio value="#{anss.verification}">
						<f:selectItem itemValue="true" itemLabel="true" />
						<f:selectItem itemValue="false" itemLabel="false" />
					</h:selectOneRadio>
					<br />
				</c:forEach>
			</c:forEach>

			<h:commandButton action="#{examenBean.doUpdate()}" value="Update">
				<f:setPropertyActionListener value="false"
					target="#{examenBean.displayUpdate}" />
				<f:setPropertyActionListener value="true"
					target="#{examenBean.displayall}" />
			</h:commandButton>
			<h:commandButton action="#{examenBean.doDelete()}" value="Delete">

				<f:setPropertyActionListener value="false"
					target="#{examenBean.displayUpdate}" />
				<f:setPropertyActionListener value="true"
					target="#{examenBean.displayall}" />
			</h:commandButton>

		</h:form>
	</ui:define>
</ui:composition>